### ISSUE TITLE
POST Request Hangs Waiting for Response

### ISSUE THREAD

**Issue by nerddtvg** [microsoftgraph/microsoft-graph-explorer-v4#555]
**Describe the bug**
When running a POST request, current example is requesting an Enterprise App to sync, the Graph Explorer never returns a response. The button to Send the request continually spins and the request history does not show the POST request.

**To Reproduce**
1. Go to https://developer.microsoft.com/en-us/graph/graph-explorer
2. Choose POST as the Method
3. Choose beta as the Version
4. Enter a URL of an AAD Enterprise App Sync Start (i.e. https://graph.microsoft.com/beta/servicePrincipals/[OBJECT ID]/synchronization/jobs/[JOB ID]/start)

**Expected behavior**
1. POST request is sent
2. History shows the record
3. Able to send another request afterwards

**Screenshots**
Screenshot showing the hanging POST request. This request was going on for at least 4 minutes. It should take about 5 seconds.

![Graph Failed Request Post](https://user-images.githubusercontent.com/5490719/82380639-6ab90d00-99ee-11ea-90df-059fa12aeaa0.png)

**Desktop (please complete the following information):**
 - OS: Win 10 2004 (Build 19041.264)
 - Browser: Microsoft Edge
 - Version: Version 83.0.478.33 (Official build) beta (64-bit)

**Comment by MIchaelMainer** [comment]
@bettirosengugi @thewahome This is being tracked with [ICM](https://portal.microsofticm.com/imp/v3/incidents/details/189893622/home)

**Comment by bettirosengugi** [comment]
@nerddtvg we have made a new deployment of Graph Explorer, version 4.1.3, please let us know if this problem still persists.

**Comment by nerddtvg** [comment]
@bettirosengugi 

I'm sorry for not responding sooner. I did just try this and still had the same problem on Edge v84. When using Dev Tools, I never see the POST request get sent to the remote server.

**Comment by ddyett** [comment]
the request won't be sent if there's no body but the button is still hanging.  re-activating.

**Comment by ddyett** [comment]
this does work in my dev branch build so possibly a caching issue, closing again

**Comment by nerddtvg** [comment]
@ddyett 

Thanks. I put '{}' in the body and it worked. I ran this with a new session and dev tools running so I disabled cache. With an empty body, it won't work. Are you saying that is fixed in a later dev release?

**Comment by ddyett** [comment]
with an empty body graph explorer will not send the response but the button won't hang.  It will instead give you an error that you need a body.

**Comment by nerddtvg** [comment]
@ddyett 

Is there a reason that changed from the original Graph Explorer which "assumed" an empty body was '{}'? There are a lot of requests that don't require a body, especially in the administrative side where we're triggering processes to run.

**Comment by ddyett** [comment]
the issue is actually in our javascript sdk which errors when this happens. we'll be putting resources back into that and see if we should be handling these cases better.  i've opened an issue in that repo to look into it.

**Comment by bettirosengugi** [comment]
Reopening this issue since it's still not resolved till we fix the bug in the SDK.

Adding a tag to show its an SDK issue.

**Comment by ddyett** [comment]
this issue covers the hang which is fixed.  the separate issue covers sdk functonality separate to this.

**Comment by MIchaelMainer** [comment]
I still observe the hang.

**Comment by ddyett** [comment]
it's in dev environment not on prod yet.

**Comment by thewahome** [comment]
Closing this as it is in dev

**Comment by MIchaelMainer** [comment]
This issue still persists.
